//
//  QUELLHTTPParametersPredicate.h
//  NSPredicateDictionary
//
//  Created by Dan Zinngrabe on 6/24/14.
//  Copyright (c) 2014 Dan Zinngrabe. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface QUELLRestServicePredicate : NSPredicate

/**
 *  Example of a factory method for generating predicates that can be understood and transformed by a generic HTTP service.
 *  The predicate returned can be represented as an NSDictionary that can easily be used as HTTP request parameters. 
 *  The implementation should serve as a reasonable starting point for implementing your own predicates to support querying 
 *  the services you are interested in supporting. 
 *
 *  The dictionary that results from calling the dictionaryRepresentation informal
 *  protocol on a predicate generated by this factory method can be used to create a URL escaped string for HTTP GET parameters,
 *  
 *
 *  @param name The tag name. This is for a fictional service, only to serve as an example.
 *
 *  @return A new predicate
 */

+ (NSPredicate *) predicateForLinksWithTag:(NSString *)name;

@end
